substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: bulb_wyze_color

esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  includes:
    - custom_components/wyzeRGBW/wyzeRGBW.h
  on_boot:
    priority: 700.0
    then:
      - light.turn_on: 
          id: ${device_name}
          color_temperature: 3200 K

esp32:
  # https://esphome.io/components/esp32
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Other required or optional ESPHome components here, like the BLE tracker and proxy below...
  
esp32_ble_tracker:
  # https://esphome.io/components/esp32_ble_tracker.html
  scan_parameters:
    active: true

bluetooth_proxy:
  # https://esphome.io/components/bluetooth_proxy.html
  active: true

output:
  - platform: ledc
    # https://esphome.io/components/output/ledc.html
    id: output_red
    pin: GPIO14
    frequency: 1220Hz
    power_supply: rgb_power
    # max_power: 0.85
  - platform: ledc
    # https://esphome.io/components/output/ledc.html
    id: output_green
    pin: GPIO26
    frequency: 1220Hz
    power_supply: rgb_power
    # max_power: 0.85
  - platform: ledc
    # https://esphome.io/components/output/ledc.html
    id: output_blue
    pin: GPIO13
    frequency: 1220Hz
    power_supply: rgb_power
    # max_power: 0.80
  - platform: ledc
    # https://esphome.io/components/output/ledc.html  
    id: output_white  
    pin: GPIO15
    frequency: 1220Hz
    # power_supply: rgb_power
    # max_power: 0.80

power_supply:
  # https://esphome.io/components/power_supply.html
  - id: rgb_power
    pin: GPIO23

light:
  # https://esphome.io/components/light/index.html
  - platform: wyzeRGBW
    id: ${device_name}
    name: ${device_name}
    cold_white_color_temperature: !secret bulb_wyze_rgb_cold
    warm_white_color_temperature: !secret bulb_wyze_rgb_warm
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_OFF
    # default_transition_length: 0.5s
    # effects: .....
